### ISSUE TITLE
Jarvis doesn't parse yaml lists correctly

### ISSUE THREAD

**Issue by lukemartinlogan** [iowarp/platform-plugins-interface#7]
Below is an example yaml being failed to parse.

```yaml
  - pkg_type: hermes_run
    pkg_name: hermes_run
    devices:
      - mount: ${HOME}/hermes_data/tier1
        size: 1g
      - mount: ${HOME}/hermes_data/tier2
        size: 1g
      - mount: ${HOME}/hermes_data/tier3
        size: 1g
      - mount: ${HOME}/hermes_data/tier4
        size: 1g
```
